version: "3.3"
services:
  judgesite:
    build:
      context: ./online-judge-site
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - mongo
      - judgeserver
    links:
      - judgeserver

  judgeserver:
    build:
      context: ./online-judge-server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - webnet
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - webnet

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - webnet
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_UERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo
    links:
      - mongo

networks:
  webnet:

volumes:
  mongodb-data: